[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
criterion = "0.5.1"
num_cpus = "1.16.0"
rayon = "1.10.0"
regex = "1.11.1"
